# Generated by Django 2.0.6 on 2018-07-28 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, verbose_name='code', unique=True)),
                ('is_base', models.BooleanField(default=False, help_text='Make this the base currency against which rates are calculated.', verbose_name='base')),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('factor', models.DecimalField(decimal_places=10, default=1.0, help_text='Specifies the difference of the currency to base one.', max_digits=30, verbose_name='factor')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='currencies.Currency')),
            ],
        ),
    ]
